services:
  postgres:
    image: postgres:15
    container_name: postgres-k1core
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres

  redis:
    image: bitnami/redis:${REDIS_VERSION}
    container_name: redis-k1core
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis_data:/bitnami/redis/data

  fastapi-django:
    build: .
    container_name: fastapi-django
    ports:
      - "8000:8000"
    depends_on:
      postgres:
          condition: service_started
      redis:
          condition: service_started
    volumes:
      - .:/app
    command: ["/bin/bash", "/app/scripts/entrypoint.sh"]

  celery-worker:
    build: .
    container_name: celery-worker
    working_dir: /app/src
    command: ["celery", "-A", "django_app.core.celery_app", "worker", "--loglevel=info"]
    restart: always
    depends_on:
      - redis
      - fastapi-django
    volumes:
      - .:/app

  celery-beat:
    build: .
    container_name: celery-beat
    working_dir: /app/src
    command: sh -c "sleep 11; celery -A django_app.core.celery_app beat --loglevel=info"
    restart: always
    depends_on:
      - redis
      - fastapi-django
    volumes:
      - .:/app

volumes:
  postgres_data:
  redis_data: